/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/rooms/{inviteCode}/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 익명 참여자의 최신 제출 조회 */
        get: operations["get"];
        /** 현재 익명 참여자의 조건 제출 또는 수정 */
        put: operations["save"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그인 없이 방과 주최자 참여 생성 */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{inviteCode}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 익명 세션으로 방 참여 */
        post: operations["join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{inviteCode}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 주최자 세션으로 입력 수집 수동 마감 */
        post: operations["close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{inviteCode}/candidates/{candidateId}/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 주최자 후보 확정 */
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{inviteCode}/analysis/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 주최자 세션으로 지연된 고정 배치 재분석 요청 */
        post: operations["retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{inviteCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 초대 코드로 공개 방 정보 조회 */
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{inviteCode}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 확정 결과 조회 */
        get: operations["result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{inviteCode}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 결정론적 모임 후보 조회 */
        get: operations["candidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{inviteCode}/candidates/unapplied-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 주최자용 미반영 입력 조회 */
        get: operations["unappliedInputs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 방 전용 수동 가능 시간 구간 */
        ManualAvailabilityDto: {
            /**
             * @description 명시 날짜 또는 주간 반복 구분
             * @enum {string}
             */
            kind?: "DATED" | "WEEKLY";
            /**
             * Format: date
             * @description DATED 구간의 지역 날짜
             */
            date?: string | null;
            /**
             * @description WEEKLY 구간의 요일
             * @enum {string|null}
             */
            day_of_week?: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY" | null;
            /**
             * @description 포함 시작 지역 시각
             * @example 18:00
             */
            start_time?: string;
            /**
             * @description 제외 종료 지역 시각
             * @example 20:00
             */
            end_time?: string;
        };
        /** @description 현재 익명 참여자의 조건 제출 또는 수정 요청 */
        SaveSubmissionRequest: {
            /** @description 선택적인 자연어 시간·장소 조건 */
            raw_text?: string | null;
            /** @description 선택적인 방 전용 가능 시간 배열 */
            manual_available_times?: components["schemas"]["ManualAvailabilityDto"][];
        };
        /** @description RFC 9457 기반 공통 오류 응답 */
        ApiProblemSchema: {
            /** @description 오류 유형 URI */
            type?: string;
            /** @description HTTP 오류 제목 */
            title?: string;
            /**
             * Format: int32
             * @description HTTP 상태 코드
             */
            status?: number;
            /** @description locale에 맞춘 사용자 표시 설명 */
            detail?: string;
            /** @description 오류가 발생한 요청 경로 */
            instance?: string;
            /** @description locale과 무관한 안정적 오류 코드 */
            code?: string;
            /**
             * Format: int32
             * @description 길이·개수 검증의 실제 값
             */
            actual?: number | null;
            /**
             * Format: int32
             * @description 길이·개수 검증의 최대 허용 값
             */
            maximum?: number | null;
            /** @description 세부 검증 거부 사유 */
            reason?: string | null;
            /** @description 필드별 검증 오류 */
            field_errors?: {
                [key: string]: string;
            } | null;
            /**
             * Format: int32
             * @description 조기 마감 확인 시 현재 제출 참여자 수
             */
            submitted_participants?: number | null;
            /**
             * Format: int32
             * @description 조기 마감 확인 시 목표 참여자 수
             */
            expected_participants?: number | null;
            /**
             * Format: date-time
             * @description 조기 마감 확인 시 제출 마감
             */
            submission_deadline?: string | null;
            /**
             * Format: int64
             * @description 요청 제한 해제까지 남은 초
             */
            retry_after_seconds?: number | null;
        };
        /** @description 현재 익명 참여자의 최신 제출 */
        SubmissionResponse: {
            /**
             * Format: int32
             * @description 불변 제출 revision
             */
            revision?: number;
            /** @description BCP 47 제출 locale */
            locale?: string;
            /** @description 현재 입력 수집 상태에서 수정 가능한지 여부 */
            editable?: boolean;
            /** @description 저장된 자연어 조건 */
            raw_text?: string | null;
            /** @description 정렬·병합된 방 전용 가능 시간 */
            manual_available_times?: components["schemas"]["ManualAvailabilityDto"][];
            /**
             * Format: date-time
             * @description 현재 revision 저장 시각
             */
            created_at?: string;
        };
        /** @description 익명 모임 방 생성 요청 */
        CreateRoomRequest: {
            /**
             * @description 모임 목적
             * @example 프로젝트 킥오프
             */
            purpose: string;
            /**
             * @description 선호 모임 방식
             * @enum {string}
             */
            meeting_mode?: "IN_PERSON" | "REMOTE" | "EITHER";
            /**
             * @description 주최자 표시 이름, 공백 제거 후 1~50자
             * @example 민수
             */
            host_display_name: string;
            /**
             * Format: int32
             * @description 자동 마감할 고유 제출 참여자 목표, 설정하면 2 이상
             */
            expected_participants?: number | null;
            /**
             * Format: date-time
             * @description 제출 마감 절대 시각
             * @example 2026-09-21T12:00:00Z
             */
            submission_deadline?: string | null;
            /** @description 자동 조건 없이 주최자가 수동으로만 마감하는지 여부 */
            manual_only?: boolean;
            /**
             * Format: date
             * @description 후보 탐색 시작 지역 날짜. 종료일과 함께 생략하면 오늘부터 14일
             */
            search_start_date?: string | null;
            /**
             * Format: date
             * @description 후보 탐색 배타적 종료 지역 날짜. 시작일과 함께 제공
             */
            search_end_date?: string | null;
        };
        /** @description 민감 식별자를 제외한 공개 방 정보 */
        RoomResponse: {
            /** @description 모임 목적 */
            purpose?: string;
            /** @description 현재 브라우저 세션의 참여 정보 */
            viewer?: components["schemas"]["ViewerParticipationResponse"];
            /** @description 공개 방 초대 코드 */
            invite_code?: string;
            /**
             * @description 선호 모임 방식
             * @enum {string}
             */
            meeting_mode?: "IN_PERSON" | "REMOTE" | "EITHER";
            /**
             * @description IANA 방 시간대
             * @example Asia/Seoul
             */
            time_zone_id?: string;
            /**
             * Format: date
             * @description 후보 탐색 시작 지역 날짜
             */
            search_start_date?: string;
            /**
             * Format: date
             * @description 후보 탐색 배타적 종료 지역 날짜
             */
            search_end_date?: string;
            /**
             * @description 탐색 날짜 범위 결정 출처
             * @enum {string}
             */
            search_range_source?: "HOST_SPECIFIED" | "DEFAULTED";
            /**
             * Format: int32
             * @description 자동 마감 참여자 목표
             */
            expected_participants?: number | null;
            /**
             * Format: date-time
             * @description 제출 마감 절대 시각
             */
            submission_deadline?: string | null;
            /** @description 수동 전용 마감 정책 여부 */
            manual_only?: boolean;
            /**
             * @description 입력 수집 상태
             * @enum {string}
             */
            collection_status?: "COLLECTING" | "CLOSED";
            /**
             * @description 입력 수집 마감 원인
             * @enum {string|null}
             */
            closure_reason?: "EXPECTED_PARTICIPANTS" | "DEADLINE" | "MANUAL" | null;
            /**
             * Format: date-time
             * @description 입력 수집 마감 절대 시각
             */
            closed_at?: string | null;
            /**
             * @description 내부 상태를 조합한 공개 진행 상태
             * @enum {string}
             */
            public_status?: "COLLECTING" | "ANALYZING" | "INSUFFICIENT_PARTICIPANTS" | "ANALYSIS_DELAYED" | "NO_MATCH" | "READY" | "READY_WITH_WARNINGS" | "CONFIRMED";
            /**
             * @description 부분 결과에서 미반영 원문을 공개하는 범위
             * @enum {string}
             */
            input_disclosure_policy?: "HOST_ON_PARTIAL_RESULT";
        };
        /** @description 현재 브라우저 세션의 방 참여 상태 */
        ViewerParticipationResponse: {
            /** @description 현재 세션이 이 방에 참여했는지 여부 */
            joined?: boolean;
            /**
             * @description 현재 세션 참여자의 역할
             * @enum {string|null}
             */
            role?: "HOST" | "MEMBER" | null;
            /** @description 현재 세션 참여자의 표시 이름 */
            display_name?: string | null;
        };
        /** @description 익명 참여 요청 */
        JoinRoomRequest: {
            /**
             * @description 참여자 표시 이름, 최초 참여에만 사용
             * @example 지수
             */
            display_name: string;
        };
        /** @description 수동 마감 요청 */
        CloseRoomRequest: {
            /** @description 자동 조건 충족 전 조기 마감을 재확인했는지 여부 */
            confirm_early?: boolean;
        };
        /** @description 후보 대표 장소 */
        CandidatePlaceResponse: {
            /**
             * Format: double
             * @description WGS84 위도
             */
            latitude?: number;
            /**
             * Format: double
             * @description WGS84 경도
             */
            longitude?: number;
            /** @description 정규화된 표시 이름 */
            display_name?: string;
        };
        /** @description 결정론적으로 계산된 모임 후보 */
        CandidateResponse: {
            /**
             * Format: int32
             * @description 후보 표시 순위
             */
            rank?: number;
            /** @description 대면 후보의 대표 장소 */
            place?: components["schemas"]["CandidatePlaceResponse"] | null;
            /** @description 요청 locale로 생성한 후보 요약 */
            summary?: string;
            /**
             * Format: uuid
             * @description 후보 식별자
             */
            candidate_id?: string;
            /**
             * @description 후보 플랜 A, B 또는 C
             * @enum {string}
             */
            plan_type?: "A" | "B" | "C";
            /**
             * @description 후보의 대면 또는 비대면 방식
             * @enum {string}
             */
            meeting_mode?: "IN_PERSON" | "REMOTE" | "EITHER";
            /**
             * Format: int32
             * @description 후보에 포함되는 참여자 수
             */
            attendance_count?: number;
            /**
             * Format: int32
             * @description 고정 배치의 전체 참여자 수
             */
            total_participants?: number;
            /** @description UTC 실제 시점 기준 후보 시간 구간 */
            time_ranges?: components["schemas"]["CandidateTimeRangeResponse"][];
        };
        /** @description 후보의 실제 UTC 시간 구간 */
        CandidateTimeRangeResponse: {
            /**
             * Format: date-time
             * @description 포함 시작 절대 시각
             */
            start_at?: string;
            /**
             * Format: date-time
             * @description 배타적 종료 절대 시각
             */
            end_at?: string;
        };
        /** @description 주최자가 확정한 최종 결과 */
        ConfirmedResultResponse: {
            /** @description 확정 후보 */
            candidate?: components["schemas"]["CandidateResponse"];
            /**
             * Format: date-time
             * @description 확정 시각
             */
            confirmed_at?: string;
        };
        /** @description 후보 생성 결과 */
        CandidateListResponse: {
            /**
             * @description 전체 또는 부분 반영 품질
             * @enum {string}
             */
            quality?: "COMPLETE" | "PARTIAL";
            /** @description 0개일 수 있는 우선순위 후보 배열 */
            candidates?: components["schemas"]["CandidateResponse"][];
            /**
             * Format: int32
             * @description 매칭에 반영된 제출 수
             */
            applied_submissions?: number;
            /**
             * Format: int32
             * @description 고정 배치의 전체 제출 수
             */
            total_submissions?: number;
            /**
             * Format: int32
             * @description 반영되지 않은 입력 수
             */
            unapplied_inputs?: number;
        };
        /** @description 주최자에게만 공개되는 미반영 입력 */
        UnappliedInputResponse: {
            /** @description 언어 중립 미반영 사유 코드 */
            reason?: string;
            /** @description 입력을 제출한 참여자의 표시 이름 */
            participant_display_name?: string;
            /** @description 후보에 반영되지 않은 원문 */
            raw_text?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: string;
            };
            cookie?: {
                meet_me_guest?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description 저장된 최신 제출 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmissionResponse"];
                };
            };
            /** @description 익명 세션 누락 또는 무효 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 참여자 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 또는 제출 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: string;
            };
            cookie?: {
                meet_me_guest?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSubmissionRequest"];
            };
        };
        responses: {
            /** @description 저장된 최신 제출 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubmissionResponse"];
                };
            };
            /** @description 입력 계약 위반 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 익명 세션 누락 또는 무효 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 참여자 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 입력 수집 종료 또는 배치 상한 초과 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 제출 요청 제한 초과 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                meet_me_guest?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
            };
        };
        responses: {
            /** @description 방 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 생성 요청 제한 초과 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 요청 제한 저장소 사용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
        };
    };
    join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: string;
            };
            cookie?: {
                meet_me_guest?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRoomRequest"];
            };
        };
        responses: {
            /** @description 기존 참여 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
            /** @description 새 참여 생성 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 이미 닫힌 방 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 참여 요청 제한 초과 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
        };
    };
    close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: string;
            };
            cookie?: {
                meet_me_guest?: string;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseRoomRequest"];
            };
        };
        responses: {
            /** @description 마감 성공 또는 기존 마감 결과 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
            /** @description 게스트 세션 누락 또는 무효 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 주최자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 조기 마감 재확인 필요 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 주최자 명령 요청 제한 초과 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 요청 제한 저장소 사용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: string;
                candidateId: string;
            };
            cookie?: {
                meet_me_guest?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description 후보 확정 또는 동일 후보 멱등 재확인 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmedResultResponse"];
                };
            };
            /** @description 익명 세션 누락 또는 무효 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 주최자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 또는 후보 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 다른 후보가 이미 확정됨 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 후보 확정 요청 제한 초과 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 요청 제한 저장소 사용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
        };
    };
    retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: string;
            };
            cookie?: {
                meet_me_guest?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description 재분석 요청 접수 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
            /** @description 익명 세션 누락 또는 무효 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 주최자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 분석 지연 상태가 아님 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 재분석 요청 제한 초과 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 요청 제한 저장소 사용 불가 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: string;
            };
            cookie?: {
                meet_me_guest?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description 방 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
            /** @description 방 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiProblemSchema"];
                };
            };
        };
    };
    result: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: string;
            };
            cookie?: {
                meet_me_guest?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description 확정 결과 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmedResultResponse"];
                };
            };
            /** @description 익명 세션 누락 또는 무효 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 참여자 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 또는 확정 결과 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
        };
    };
    candidates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: string;
            };
            cookie?: {
                meet_me_guest?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description 후보 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateListResponse"];
                };
            };
            /** @description 익명 세션 누락 또는 무효 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 참여자 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 후보 준비 전 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
        };
    };
    unappliedInputs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteCode: string;
            };
            cookie?: {
                meet_me_guest?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description 미반영 입력 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnappliedInputResponse"][];
                };
            };
            /** @description 익명 세션 누락 또는 무효 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 주최자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 방 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
            /** @description 부분 결과 준비 전 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiProblemSchema"];
                };
            };
        };
    };
}
